# name: ci

# on:
#   push:
#     branches:
#       - vited

# jobs:
#   ci:
#     runs-on: ubuntu-latest

#     steps:

#     - uses: actions/checkout@v3
#     - name: Install Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '16.x'

#     - name: Select the proper .env file
#       run: mv .env.dev .env

#     - name: Install dependencies 
#       run: yarn install

#     - name: Build the project 
#       run: yarn run build

